/**
 * bill-generation.service.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Shared logic for generating monthly bills for a customer.
 * Used by:
 *   - POST /api/customers  (auto-generate all past months on client creation)
 *   - POST /api/bills/bulk-generate  (on-demand catch-up for existing clients)
 *
 * Design decisions:
 *   - Accepts an already-loaded customer document so callers control DB fetching.
 *   - Accepts an already-loaded session userId for audit trail.
 *   - Increments BillType.lastNumber sequentially per bill inside a for-loop
 *     (intentional — avoids race-condition gaps from Promise.all).
 *   - On any single-bill failure the counter is reverted and the error is
 *     recorded; other months still proceed.
 */

import mongoose from "mongoose";
import Bill from "@/lib/models/Bill";
import BillType from "@/lib/models/BillType";
import FinancialYear from "@/lib/models/FinancialYear";
import { calculateBill } from "@/lib/billing-engine";
import type { ICustomer, ICustomerService } from "@/lib/models/Customer";

// ─── Constants ────────────────────────────────────────────────────────────────

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July",    "August",   "September", "October", "November", "December",
] as const;

const OBJECTID_RE = /^[a-f\d]{24}$/i;

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GeneratedBill {
  month: string;
  year: number;
  invoiceNumber: string;
  grandTotal: number;
}

export interface SkippedMonth {
  month: string;
  year: number;
  reason: string;
  existingInvoice?: string;
}

export interface FailedMonth {
  month: string;
  year: number;
  error: string;
}

export interface BulkGenerateResult {
  created: GeneratedBill[];
  skipped: SkippedMonth[];
  errors:  FailedMonth[];
}

interface PendingMonth {
  month: string;
  year: number;
  /** ISO date string — last day of the billing month, used as invoice date */
  invoiceDate: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns every month from billingStartDate up to (not including) the current
 * month that falls within [fyStart, fyEnd].
 *
 * "Up to but not including current month" — the current month's bill is
 * generated by the normal "Generate Next Bill" flow once the month ends.
 */
export function getPendingMonths(
  billingStartDate: Date,
  fyStart: Date,
  fyEnd: Date,
): PendingMonth[] {
  const today = new Date();
  today.setDate(1);
  today.setHours(0, 0, 0, 0);

  const cursor = new Date(billingStartDate);
  cursor.setDate(1);
  cursor.setHours(0, 0, 0, 0);

  // Clamp to FY start — can never go before FY open date
  const fyStartNorm = new Date(fyStart);
  fyStartNorm.setHours(0, 0, 0, 0);
  if (cursor < fyStartNorm) cursor.setTime(fyStartNorm.getTime());

  const fyEndNorm = new Date(fyEnd);
  fyEndNorm.setHours(23, 59, 59, 999);

  const result: PendingMonth[] = [];

  while (cursor <= today) {
    if (cursor >= fyStartNorm && cursor <= fyEndNorm) {
      const month = MONTHS[cursor.getMonth()];
      const year  = cursor.getFullYear();
      // Invoice date = last calendar day of that billing month
      const lastDay = new Date(year, cursor.getMonth() + 1, 0);
      result.push({ month, year, invoiceDate: lastDay.toISOString().split("T")[0] });
    }
    cursor.setMonth(cursor.getMonth() + 1);
  }

  return result;
}

/**
 * Builds the service input for ONE customer service for calculateBill().
 *
 * Electricity past bills: generated with 0 units so the admin can edit the
 * actual meter reading later. A note is attached for visibility.
 */
function buildOneServiceInput(
  svc: ICustomerService,
  month: string,
  year: number,
) {
  const isElec   = (svc.type ?? "").toLowerCase() === "electricity";
  const calcType = (isElec ? "METER" : "QUANTITY_RATE") as "METER" | "QUANTITY_RATE";
  const quantity = isElec ? 0 : (Number(svc.units) || 1);
  const notes    = isElec
    ? `Auto-generated for ${month} ${year}. Enter actual meter reading to update.`
    : undefined;

  const typeName = svc.type || "Service";
  return {
    serviceId:       typeName,
    serviceName:     typeName.charAt(0).toUpperCase() + typeName.slice(1),
    serviceCode:     typeName.toUpperCase().slice(0, 4),
    calculationType: calcType,
    quantity,
    unit:        isElec ? "kWh" : "unit",
    rate:        Number(svc.rate) || 0,
    isTaxable:   svc.isTaxable !== false,
    gstRate:     Number(svc.gstRate) || 0,
    notes,
  };
}

// ─── Main exported function ───────────────────────────────────────────────────

/**
 * Generates all missing monthly bills for a customer from their billingStartDate
 * up to (not including) the current month, constrained to the active FY.
 *
 * RULE 3 — One bill PER SERVICE per month (NOT one combined bill).
 * Example: 3 services × 2 months = 6 independent unpaid bills.
 *
 * @param customer  - Mongoose lean or hydrated customer document
 * @param userId    - session.user.id for audit fields
 * @param options.existingBillKeys - optional pre-fetched set of
 *                    "Month-Year-ServiceName" strings to skip.
 */
export async function generatePastBills(
  customer: ICustomer,
  userId: string,
  options: { existingBillKeys?: Set<string> } = {},
): Promise<BulkGenerateResult> {
  const result: BulkGenerateResult = { created: [], skipped: [], errors: [] };

  // ── Prerequisites ──────────────────────────────────────────────────────────
  if (!customer.billingStartDate) return result;
  if (!customer.services?.length) return result;
  if (customer.billingType !== "monthly") {
    return result;
  }

  const services = customer.services;
  if (services.length === 0) return result;

  // ── Active FY ──────────────────────────────────────────────────────────────
  const fy = await FinancialYear.findOne({ isActive: true, isClosed: false }).lean();
  if (!fy) return result;

  const fyStart = new Date(fy.startDate);
  const fyEnd   = new Date(fy.endDate);

  // ── Bill type ──────────────────────────────────────────────────────────────
  const billTypeLean =
    (await BillType.findOne({ isActive: true }).lean()) ??
    (await BillType.findOne({}).lean());
  if (!billTypeLean) return result;

  // ── Pending months ─────────────────────────────────────────────────────────
  const pendingMonths = getPendingMonths(
    new Date(customer.billingStartDate),
    fyStart,
    fyEnd,
  );
  if (pendingMonths.length === 0) return result;

  // ── SERVICE-LEVEL duplicate detection ──────────────────────────────────────
  // Key format: `${Month}-${Year}-${ServiceName}` (one bill per service per month)
  let existingSvcKeys = options.existingBillKeys;
  if (!existingSvcKeys) {
    const years = [...new Set(pendingMonths.map((m) => m.year))];
    const existing = await Bill.find({
      customerId: customer._id as mongoose.Types.ObjectId,
      billingYear: { $in: years },
      status: { $ne: "cancelled" },
    })
      .select("billingMonth billingYear invoiceNumber items")
      .lean();

    existingSvcKeys = new Set<string>();
    for (const b of existing) {
      const svcNames = b.items?.length
        ? b.items.map((it) => (it.serviceName || "").toLowerCase())
        : ["__combined__"];
      for (const sn of svcNames) {
        existingSvcKeys.add(`${b.billingMonth}-${b.billingYear}-${sn}`);
      }
      // If bill has no items (legacy combined bill), mark entire month as done
      if (!b.items || b.items.length === 0) {
        for (const svc of services) {
          existingSvcKeys.add(`${b.billingMonth}-${b.billingYear}-${(svc.type || "").toLowerCase()}`);
        }
      }
      // Populate skipped list with per-service entries
      const pm = pendingMonths.find(
        (m) => m.month === b.billingMonth && m.year === b.billingYear,
      );
      if (pm) {
        for (const sn of svcNames) {
          result.skipped.push({
            month: b.billingMonth,
            year:  b.billingYear,
            reason: sn === "__combined__"
              ? "Combined bill already exists"
              : `Bill for service already exists (${sn})`,
            existingInvoice: b.invoiceNumber,
          });
        }
      }
    }
  }

  // ── Build list of per-service creations: (month × service) ─────────────────
  interface PerServiceTask {
    month: string;
    year: number;
    invoiceDate: string;
    service: ICustomerService;
    serviceName: string;
    key: string;
  }
  const tasks: PerServiceTask[] = [];

  for (const { month, year, invoiceDate } of pendingMonths) {
    for (const svc of services) {
      const svcName = (svc.type || "service").toLowerCase();
      const key     = `${month}-${year}-${svcName}`;
      if (existingSvcKeys.has(key)) {
        // Avoid double-adding to skipped (already added above when existing present)
        continue;
      }
      tasks.push({ month, year, invoiceDate, service: svc, serviceName: svcName, key });
    }
  }
  if (tasks.length === 0) return result;

  // ── Create ONE BILL PER SERVICE sequentially ───────────────────────────────
  for (const { month, year, invoiceDate, service, serviceName, key } of tasks) {
    try {
      const bt = await BillType.findByIdAndUpdate(
        billTypeLean._id,
        { $inc: { lastNumber: 1 } },
        { new: true },
      );
      if (!bt) throw new Error("BillType not found during increment");

      const invoiceNumber = `${bt.prefix}/${fy.name}/${String(bt.lastNumber).padStart(6, "0")}`;

      const oneSvc   = buildOneServiceInput(service, month, year);
      const billing  = calculateBill({ services: [oneSvc] });

      // Strip non-ObjectId serviceIds (e.g. plain strings like "electricity")
      const items = billing.items.map((item) => ({
        ...item,
        serviceId: OBJECTID_RE.test(item.serviceId ?? "")
          ? item.serviceId
          : undefined,
      }));

      const invoiceDateObj = new Date(invoiceDate);
      const dueDateObj     = new Date(invoiceDateObj);
      dueDateObj.setDate(dueDateObj.getDate() + 15);

      await Bill.create({
        invoiceNumber,
        billTypeId:       bt._id,
        financialYearId:  fy._id,
        customerId:       customer._id,
        invoiceDate:      invoiceDateObj,
        dueDate:          dueDateObj,
        billingMonth:     month,
        billingYear:      year,
        ...billing,
        items,
        status:           "unpaid",
        paidAmount:       0,
        outstandingAmount: billing.grandTotal,
        notes: `Auto-generated ${serviceName} bill for ${month} ${year}.`,
        createdBy: new mongoose.Types.ObjectId(userId),
      });

      result.created.push({ month, year, invoiceNumber, grandTotal: billing.grandTotal });
      existingSvcKeys.add(key);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      const isdup =
        msg.toLowerCase().includes("duplicate") ||
        (e as { code?: number })?.code === 11000;

      if (isdup) {
        result.skipped.push({
          month,
          year,
          reason: `Duplicate — ${serviceName} bill already exists for ${month} ${year}`,
        });
        await BillType.findByIdAndUpdate(
          billTypeLean._id,
          { $inc: { lastNumber: -1 } },
        ).catch(() => {});
      } else {
        result.errors.push({ month, year, error: `[${serviceName}] ${msg}` });
        await BillType.findByIdAndUpdate(
          billTypeLean._id,
          { $inc: { lastNumber: -1 } },
        ).catch(() => {});
      }
    }
  }

  return result;
}

// ─── FY validation helpers (used by both API and frontend) ────────────────────

/**
 * Returns the active FY date bounds for use in validation.
 * Returns null if no active FY exists.
 */
export async function getActiveFYBounds(): Promise<{
  fyId:    string;
  fyName:  string;
  fyStart: Date;
  fyEnd:   Date;
} | null> {
  const fy = await FinancialYear.findOne({ isActive: true, isClosed: false }).lean();
  if (!fy) return null;
  return {
    fyId:    fy._id.toString(),
    fyName:  fy.name,
    fyStart: new Date(fy.startDate),
    fyEnd:   new Date(fy.endDate),
  };
}

/**
 * Validates a billingStartDate string against FY rules.
 * Returns an error message string, or null if valid.
 *
 * Rules:
 *   1. Date must be ≥ fyStart (cannot be before the active FY opened)
 *   2. Date must be ≤ today   (cannot be a future date)
 */
export function validateBillingStartDate(
  dateStr: string,
  fyStart: Date,
  fyEnd:   Date,
): string | null {
  const date  = new Date(dateStr);
  const today = new Date();
  today.setHours(23, 59, 59, 999); // inclusive of today

  const fyStartNorm = new Date(fyStart);
  fyStartNorm.setHours(0, 0, 0, 0);

  if (isNaN(date.getTime())) return "Invalid billing start date.";

  if (date < fyStartNorm) {
    return (
      `Billing start date must be within the active Financial Year ` +
      `(${fyStartNorm.toLocaleDateString("en-IN")} – Today). ` +
      `Dates before ${fyStartNorm.toLocaleDateString("en-IN")} belong to a closed financial year.`
    );
  }

  if (date > today) {
    return (
      `Billing start date cannot be a future date. ` +
      `Please select a date between ${fyStartNorm.toLocaleDateString("en-IN")} and today.`
    );
  }

  void fyEnd; // fyEnd unused in validation but kept for interface symmetry
  return null;
}
